source: .
exclude: [ "*" ]
destination: target
keep_files: [ renditions ]

include: [ index.html ]

image_tag:
  haus_gallery:
    path: photos/haus-gallery
    geometries: [ x200, x1000 ]
    output_path_format: "%{filepath}-%{width}x%{height}.%{ext}"
